spring:
  application:
    name: tpgerenciaconfig
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect